#!/bin/sh
echo "IMMETTI LE DIMENSIONI DEI PIPE CHE FORMANO IL QUADRATO"
read size
clear
for (( i = 1; i <= size; i++ )); do
    for (( j = 1; j <= size; j++ )); do

        if [ "$i" == 1 ] || [ "$i" == "$size" ] || [ "$j" == 2 ] || [ "$j" == "$size" ]
         then
            #DICHIARIAMO
            tput cup $i $j
            echo "|"
        fi
     done
done
